<?php
use yii\bootstrap5\Html;
$this->title = 'Eszköztár';
$today = date('Y-m-d');
$week = date('Y-m-d', strtotime('+7 days'));
$statusLabels = [0 => 'Elérhető', 1 => 'Kiadva', 2 => 'Szerviz', 3 => 'Selejt'];
$statusClasses = [0 => 'status-available', 1 => 'status-lended', 2 => 'status-maintenance', 3 => 'status-maintenance'];
$csrfInput = Html::hiddenInput('_csrf', Yii::$app->request->getCsrfToken());
?>
<div class="inventory-shell">
    <section class="inventory-hero"><div><p class="eyebrow">BELSŐ ESZKÖZTÁR</p><h1>Mindig tudd, kinél van.</h1><p class="hero-copy">Laptopok, projektorok, kamerák és szerszámok egyetlen aktuális nézetben.</p></div><div class="hero-mark">ASSET<br><strong>ROOM</strong></div></section>
        <section class="metrics"><div><span>Összes eszköz</span><strong><?= $report['total'] ?></strong></div><div><span>Elérhető</span><strong class="green"><?= $report['available'] ?></strong></div><div><span>Kiadva</span><strong class="amber"><?= $report['lended'] ?></strong></div><div><span>Szervizben</span><strong class="gray"><?= $report['maintenance'] ?></strong></div><div><span>Ma visszavárt</span><strong class="red"><?= $report['dueToday'] ?></strong></div><div><span>Késik</span><strong class="red"><?= $report['overdue'] ?></strong></div></section>
    <?php if ($canEdit): ?>
    <section class="inventory-admin">
        <form class="admin-card" method="post"><?= $csrfInput ?><?= Html::hiddenInput('action', 'create_equipment') ?>
            <div class="section-heading"><div><p class="eyebrow">LELTÁR BŐVÍTÉSE</p><h2>Új eszköz hozzáadása</h2></div></div>
            <div class="admin-fields"><label>Leltári szám<input type="text" name="inventory_no" maxlength="30" required></label><label>Eszköz<input type="text" name="equipment_name" maxlength="120" required></label><label>Kategória<select name="category_id" required><option value="">Válassz kategóriát</option><?php foreach ($categories as $category): ?><option value="<?= $category['id'] ?>"><?= Html::encode($category['name']) ?></option><?php endforeach; ?></select></label><label>Kaució (Ft)<input type="number" name="deposit" min="0" step="100" value="0"></label></div>
            <div class="admin-actions"><button class="action-button" <?= $categories ? '' : 'disabled' ?>>Eszköz mentése</button><?php if (!$categories): ?><span class="muted">Előbb hozz létre kategóriát.</span><?php endif; ?></div>
        </form>
        <div class="admin-card">
            <div class="section-heading"><div><p class="eyebrow">KATEGÓRIÁK</p><h2>Kategóriák</h2></div><?= Html::a('Új kategória', ['/category/create'], ['class' => 'link-button']) ?></div>
            <div class="category-list"><?php foreach ($categoryStats as $category): ?><div class="category-row"><div><strong><?= Html::encode($category['name']) ?></strong><span><?= (int) $category['equipment_count'] ?> eszköz</span></div><?php if ((int) $category['equipment_count'] === 0): ?><form method="post" onsubmit="return confirm('Biztosan törlöd ezt a kategóriát?');"><?= $csrfInput ?><?= Html::hiddenInput('action', 'delete_category') ?><?= Html::hiddenInput('category_id', $category['id']) ?><button class="link-button danger">Törlés</button></form><?php else: ?><span class="muted">Nem törölhető, eszköz tartozik hozzá</span><?php endif; ?></div><?php endforeach; ?><?php if (!$categoryStats): ?><p class="muted">Még nincs kategória.</p><?php endif; ?></div>
        </div>
    </section>
    <?php endif; ?>
    <div class="content-grid"><section><div class="section-heading"><div><p class="eyebrow">ESZKÖZÖK</p><h2>Teljes leltár</h2></div><span class="count-pill"><?= $report['total'] ?> tétel</span></div><div class="equipment-list">
        <form class="status-filter catalog-filters" method="get"><label>Állapot<select name="status" onchange="this.form.submit()"><option value="" <?= $statusFilter === '' ? 'selected' : '' ?>>Mindegyik</option><option value="out" <?= $statusFilter === 'out' ? 'selected' : '' ?>>Kiadva</option><option value="in" <?= $statusFilter === 'in' ? 'selected' : '' ?>>Elérhető</option><option value="maintenance" <?= $statusFilter === 'maintenance' ? 'selected' : '' ?>>Szerviz</option></select></label><label>Ember<select name="lender_id" onchange="this.form.submit()"><option value="">Minden ember</option><?php foreach ($lenders as $lender): ?><option value="<?= $lender['id'] ?>" <?= (string) $lenderFilter === (string) $lender['id'] ? 'selected' : '' ?>><?= Html::encode($lender['full_name']) ?></option><?php endforeach; ?></select></label><label>Kategória<select name="category_id" onchange="this.form.submit()"><option value="">Minden kategória</option><?php foreach ($categories as $category): ?><option value="<?= $category['id'] ?>" <?= (string) $categoryFilter === (string) $category['id'] ? 'selected' : '' ?>><?= Html::encode($category['name']) ?></option><?php endforeach; ?></select></label></form>
        <?php foreach ($equipment as $item): ?><article class="equipment-row"><div class="item-icon"><?= strtoupper(substr($item['category_name'], 0, 2)) ?></div><div class="item-main"><strong><?= Html::encode($item['inventory_no']) ?> · <?= Html::encode($item['name']) ?></strong><span><?= Html::encode($item['category_name']) ?> · <?= Html::encode($item['description'] ?: 'Nincs leírás') ?></span><?php if ((int) $item['status'] === 1 && $item['active_lender_name']): ?><small class="loan-meta">Kiadva: <?= Html::encode($item['active_lender_name']) ?> · <?= Html::encode($item['active_loaned_at']) ?></small><?php endif; ?></div><span class="status <?= $statusClasses[$item['status']] ?>"><?= $statusLabels[$item['status']] ?></span><div class="row-actions"><?php if ($canEdit && (int) $item['status'] === 0): ?><?= Html::a('Kiadás', ['/loan/create', 'equipment_id' => $item['id']], ['class' => 'action-button']) ?><form method="post"><?= $csrfInput ?><?= Html::hiddenInput('action', 'maintenance') ?><?= Html::hiddenInput('equipment_id', $item['id']) ?><button class="link-button" style="margin-left: 2px; margin-top: 5px;">Szervizbe</button></form><?php elseif ($canEdit && (int) $item['status'] === 1 && $item['active_loan_id']): ?><?= Html::beginForm(['/loan/return', 'id' => $item['active_loan_id']], 'post') ?><?= $csrfInput ?><button class="link-button">Visszavétel</button><?= Html::endForm() ?><?php elseif ($canEdit && (int) $item['status'] === 2): ?><form method="post"><?= $csrfInput ?><?= Html::hiddenInput('action', 'maintenance_return') ?><?= Html::hiddenInput('equipment_id', $item['id']) ?><button class="link-button">Visszavétel</button></form><?php else: ?><span class="muted">Csak megtekintés</span><?php endif; ?><?php if ($canEdit && (int) $item['status'] !== 1): ?><form method="post" onsubmit="return confirm('Biztosan törlöd az eszközt? Ha volt már kölcsönzése, törlés helyett selejt státuszt kap.');"><?= $csrfInput ?><?= Html::hiddenInput('action', 'delete_equipment') ?><?= Html::hiddenInput('equipment_id', $item['id']) ?><button class="link-button danger">Törlés</button></form><?php endif; ?></div></article><?php endforeach; ?>
    </div></section><aside><div class="section-heading"><div><p class="eyebrow">AKTUÁLIS</p><h2>Kinél van?</h2></div></div><?php foreach ($loans as $loan): ?><div class="loan-card"><div><strong><?= Html::encode($loan['inventory_no']) ?> · <?= Html::encode($loan['equipment_name']) ?></strong><span><?= Html::encode($loan['full_name']) ?> · <?= Html::encode($loan['email']) ?></span></div><time class="<?= $loan['due_at'] < $today ? 'overdue' : '' ?>"><?= Html::encode($loan['due_at']) ?></time></div><?php endforeach; ?><?php if (!$loans): ?><p class="muted">Nincs aktív kölcsönzés.</p><?php endif; ?><div class="report-note"><strong><?= $report['lended'] ?> aktív kölcsönzés</strong><span>Állapotjelentés a mai napra, <?= $today ?>.</span></div><div class="movement-list"><p class="eyebrow">UTOLSÓ MOZGÁSOK</p><?php foreach ($movements as $movement): ?><div><span><?= Html::encode($movement['equipment_name']) ?></span><small><?= Html::encode($movement['full_name']) ?> · <?= $movement['returned_at'] ? 'Visszavéve' : 'Kiadva' ?></small></div><?php endforeach; ?></div></aside></div>
</div>
<div class="modal fade" id="lendModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post"><?= $csrfInput ?><div class="modal-header"><h2>Kiadás rögzítése</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p id="selected-equipment" class="selected-equipment"></p><?= Html::hiddenInput('action', 'lend') ?><?= Html::hiddenInput('equipment_id', '', ['id' => 'equipment-id']) ?><label>Lender<select name="lender_id" required><option value="">Válassz lendert</option><?php foreach ($lenders as $lender): ?><option value="<?= $lender['id'] ?>"><?= Html::encode($lender['full_name']) ?></option><?php endforeach; ?></select></label><div class="date-fields"><label>Elvitel<input type="date" name="starts_on" value="<?= $today ?>" required></label><label>ozás<input type="date" name="due_on" value="<?= $week ?>" required></label></div></div><div class="modal-footer"><button type="button" class="link-button" data-bs-dismiss="modal">Mégse</button><button class="action-button">Kölcsönzés mentése</button></div></form></div></div></div>
<?php $this->registerJs("$('#lendModal').on('show.bs.modal', function (event) { var button = $(event.relatedTarget); $('#equipment-id').val(button.data('equipment-id')); $('#selected-equipment').text(button.data('equipment-name')); });"); ?>
