<?php
use yii\bootstrap5\Html;
$this->title = 'Eszköztár';
$today = date('Y-m-d');
$week = date('Y-m-d', strtotime('+7 days'));
$statusLabels = [0 => 'Elérhető', 1 => 'Kölcsönözve', 2 => 'Szerviz', 3 => 'Selejt'];
$statusClasses = [0 => 'status-available', 1 => 'status-borrowed', 2 => 'status-maintenance', 3 => 'status-maintenance'];
?>
<div class="inventory-shell">
    <section class="inventory-hero"><div><p class="eyebrow">BELSŐ ESZKÖZTÁR</p><h1>Mindig tudd, kinél van.</h1><p class="hero-copy">Laptopok, projektorok, kamerák és szerszámok egyetlen aktuális nézetben.</p></div><div class="hero-mark">ASSET<br><strong>ROOM</strong></div></section>
    <section class="metrics"><div><span>Összes eszköz</span><strong><?= $report['total'] ?></strong></div><div><span>Szabadon vihető</span><strong class="green"><?= $report['available'] ?></strong></div><div><span>Kint van</span><strong class="amber"><?= $report['borrowed'] ?></strong></div><div><span>Ma visszavárt</span><strong class="red"><?= $report['dueToday'] ?></strong></div></section>
    <div class="content-grid"><section><div class="section-heading"><div><p class="eyebrow">ESZKÖZÖK</p><h2>Teljes leltár</h2></div><span class="count-pill"><?= $report['total'] ?> tétel</span></div><div class="equipment-list">
        <?php foreach ($equipment as $item): ?><article class="equipment-row"><div class="item-icon"><?= strtoupper(substr($item['category_name'], 0, 2)) ?></div><div class="item-main"><strong><?= Html::encode($item['inventory_no']) ?> · <?= Html::encode($item['name']) ?></strong><span><?= Html::encode($item['category_name']) ?> · <?= Html::encode($item['description'] ?: 'Nincs leírás') ?></span></div><span class="status <?= $statusClasses[$item['status']] ?>"><?= $statusLabels[$item['status']] ?></span><div class="row-actions"><?php if ($canEdit && (int) $item['status'] === 0): ?><button class="action-button" data-bs-toggle="modal" data-bs-target="#lendModal" data-equipment-id="<?= $item['id'] ?>" data-equipment-name="<?= Html::encode($item['name']) ?>">Kiadás</button><form method="post"><?= Html::hiddenInput('action', 'maintenance') ?><?= Html::hiddenInput('equipment_id', $item['id']) ?><button class="link-button">Szervizbe</button></form><?php elseif ($canEdit && (int) $item['status'] === 1): ?><form method="post"><?= Html::hiddenInput('action', 'return') ?><?= Html::hiddenInput('equipment_id', $item['id']) ?><button class="link-button">Visszavétel</button></form><?php else: ?><span class="muted">Csak megtekintés</span><?php endif; ?></div></article><?php endforeach; ?>
    </div></section><aside><div class="section-heading"><div><p class="eyebrow">AKTUÁLIS</p><h2>Kinél van?</h2></div></div><?php foreach ($loans as $loan): ?><div class="loan-card"><div><strong><?= Html::encode($loan['inventory_no']) ?> · <?= Html::encode($loan['equipment_name']) ?></strong><span><?= Html::encode($loan['full_name']) ?> · <?= Html::encode($loan['email']) ?></span></div><time class="<?= $loan['due_at'] < $today ? 'overdue' : '' ?>"><?= Html::encode($loan['due_at']) ?></time></div><?php endforeach; ?><?php if (!$loans): ?><p class="muted">Nincs aktív kölcsönzés.</p><?php endif; ?><div class="report-note"><strong><?= $report['borrowed'] ?> aktív kölcsönzés</strong><span>Állapotjelentés a mai napra, <?= $today ?>.</span></div><div class="movement-list"><p class="eyebrow">UTOLSÓ MOZGÁSOK</p><?php foreach ($movements as $movement): ?><div><span><?= Html::encode($movement['equipment_name']) ?></span><small><?= Html::encode($movement['full_name']) ?> · <?= $movement['returned_at'] ? 'Visszavéve' : 'Kiadva' ?></small></div><?php endforeach; ?></div></aside></div>
</div>
<div class="modal fade" id="lendModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post"><div class="modal-header"><h2>Kiadás rögzítése</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p id="selected-equipment" class="selected-equipment"></p><?= Html::hiddenInput('action', 'lend') ?><?= Html::hiddenInput('equipment_id', '', ['id' => 'equipment-id']) ?><label>Kölcsönző<select name="borrower_id" required><option value="">Válassz kölcsönzőt</option><?php foreach ($borrowers as $borrower): ?><option value="<?= $borrower['id'] ?>"><?= Html::encode($borrower['full_name']) ?></option><?php endforeach; ?></select></label><div class="date-fields"><label>Elvitel<input type="date" name="starts_on" value="<?= $today ?>" required></label><label>Visszahozás<input type="date" name="due_on" value="<?= $week ?>" required></label></div></div><div class="modal-footer"><button type="button" class="link-button" data-bs-dismiss="modal">Mégse</button><button class="action-button">Kölcsönzés mentése</button></div></form></div></div></div>
<?php $this->registerJs("$('#lendModal').on('show.bs.modal', function (event) { var button = $(event.relatedTarget); $('#equipment-id').val(button.data('equipment-id')); $('#selected-equipment').text(button.data('equipment-name')); });"); ?>
